version: '3.9'

services:
  gaia:
    container_name: gaia_core
    build: .
    ports:
      - "7860:7860"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - GAIA_ENV=production
    restart: unless-stopped